language: c
install: 
    - sudo apt-get install python3-sphinx python3-nose gettext python3-setuptools valgrind
    - sudo apt-get install libblkid-dev libelf-dev libglib2.0-dev  libjson-glib-dev
    - sudo easy_install3 pip
    - sudo /usr/local/bin/pip install sphinx_bootstrap_theme
compiler:
  - clang
  - gcc
notifications:
  email:
    - sahib@online.de
    - thomas_d_j@yahoo.com.au

script: scons && export USE_VALGRIND=1 && sudo nosetests3
