language: c

install:
    - sudo apt-get update
    - sudo apt-get install python3-sphinx gettext python3-setuptools
    - sudo apt-get install libblkid-dev libelf-dev libglib2.0-dev libjson-glib-dev
    - sudo apt-get install clang
    - sudo easy_install3 $(cat test-requirements.txt)

compiler:
  - clang
  - gcc

notifications:
  email:
    - sahib@online.de
    - thomas_d_j@yahoo.com.au

script:
    - scons VERBOSE=1 DEBUG=1 O=release
    - scons config
    - export RM_TS_PRINT_CMD=1
    - export RM_TS_PEDANTIC=0
    - sudo -E nosetests -s -v -a '!slow'
